### PR TITLE
Fixed 249 mags and added Spare barrels

### PR DESCRIPTION
**Pull request by VexA3**
**When merged this pull request will:**
- Update Starter Crate Supplies with correct 249 mags #443 
- Add Spare Barrels #338 

- Respect the [Development Guidelines](https://github.com/7Cav/cScripts/wiki/Code-and-development-policy)

### CODE REVIEW

**Comment by Robot-Panda15** [comment]
Charlie Company (and B Troop will likely follow suit) uses a different 249 box. They use the 200rnd coyote soft pouch - "rhsusf_200rnd_556x45_mixed_soft_pouch_coyote"

**Comment by Robot-Panda15** [comment]
I'd also recommend checking out #449 in regards to this

**Comment by ColdEvul** [comment]
shifting merge branch stand

**Comment by ColdEvul** [comment]
This have been added to the starter crate rework https://github.com/7Cav/cScripts/pull/449 manually closing this.
checkout https://github.com/7Cav/cScripts/tree/Starter-Crate-Reword for additions and update the rework of the crate :D

**Pull request closed without merging**
