### PR TITLE
ACE-Update Settings Fix

### PR DESCRIPTION
**Pull request by Elemtael**
- New CBA settings with ACE update.

### CODE REVIEW

**Comment by pool011** [comment]
@Zarenx we have a hot fix with the new cba settings for the new mod updates. Thought you might want to take a look.

**Comment by deathmachine221** [comment]
We have a test file right now uploaded to Stratis as Testyter (ask westcott) it has the current CBA settings listed in this pull request.
@Elemtael @Zarenx

**Comment by AndreasBrostrom** [comment]
Monitoring.
The cba settings in this file are not in s hurry to be updated.

The export list don't looks like it is sorted properly either from first glance.

**Comment by pool011** [comment]
They need cleanup, but we are adding KAT medical so the setting needs to be updated ASAP so we have the appropriate settings there.

**Comment by Zarenx** [comment]
@pool Looks alright, but why are we redoing everything that was updated in the latest CBA fix? 

Is a old CBA Settings file being used for the PR or do we want ace ballistics, more fragments, more medical litter, shorter refuel, no TFAR settings etc?

**Comment by AndreasBrostrom** [comment]
> @pool011 Looks alright, but why are we redoing everything that was updated in the latest CBA fix?
> 
> Is a old CBA Settings file being used for the PR or do we want ace ballistics, more fragments, more medical litter, shorter refuel, no TFAR settings etc?

The diff is missleading reasoning being that the export have not been directly applied and have been rearaged and been some what tampered with.

I will put my self to merge all this including #1053 togehter once all the mods have been updated to function current ACE.

**Pull request closed without merging**
