### PR TITLE
Initial commit of Orbat framework

### PR DESCRIPTION
**Pull request by Whitsel**
Still needs graphics added to CavAddon and file pathing for texture and insignias in cfgOrbat. Likely reduce size to only 1BN and adjust text to include radio channels or other useful information. Compositions will need to be updated with preconfigured orbat modules to facilitate ease of use for mission makers

**When merged this pull request will:**
- Create a framework for in-game orbat

### CODE REVIEW

**Comment by ColdEvul** [comment]
Feel we can do this in the mod instead.
Also the paths to images are refering mission root.

**Comment by Whitsel** [comment]
> Feel we can do this in the mod instead.
> Also the paths to images are refering mission root.

Yes, it's just a placeholder framework for now till there are actual paths. I'm not sure how to config this in the mod the mod though

**Comment by ColdEvul** [comment]
> > Feel we can do this in the mod instead.
> > Also the paths to images are refering mission root.
> 
> Yes, it's just a placeholder framework for now till there are actual paths. I'm not sure how to config this in the mod the mod though

I make the addon so you can fix the paths :)

**Comment by ColdEvul** [comment]
https://github.com/7Cav/7CavAddon/pull/167 PR taking over

**Pull request closed without merging**
