### PR TITLE
Alpha company insignia/menu reorganization

### PR DESCRIPTION
**Pull request by RaynorD**
- Added Alpha Company insignia to images and macros
- Reorganized selection/interaction menu (cav patch in scroll select, each company has ace interaction submenu)

### CODE REVIEW

**Comment by ColdEvul** [comment]
Some indentation fixes needed else it looks awesome :)

**Comment by RaynorD** [comment]
Like this?
--Platoon insignia
----Squad insignia
----Squad insignia

**Comment by ColdEvul** [comment]
You use tab instead of 4 spaces :)
Have not got the robot to fix this manually yet. :)

**Comment by RaynorD** [comment]
Are there problems with using tab? I've always used tab and never had any 
issues.

**Comment by ColdEvul** [comment]
Well it will look like a cluster fuck when you look at the code when mixing space and tabs.

I'll gonna make sure a robot fix that for future builds. Same goes for white spaces.

**Pull request merged**
