### PR TITLE
Updated All Loadouts for KAM Update

### PR DESCRIPTION
**Pull request by Robot-Panda15**
- [x] +Add Splints to all Viking Loadouts
- [x] +Add Demolitions and Firing Devices to all arsenals
- [x] +Add ACE Flashbangs to all arsenals
- [x] +Add all spraypaint colors
- [ ] +Add vanilla mine detectors for Stryker Crew
- [x] +Add Earplugs to inventory
- [x] +Add Glock 17 Mags
- [ ] +Add SDM Ammo to resupply crates
- [ ] +Add Painkillers to resupply crates

- [x] >Allow Team Leaders with Standalone M320s to have access to underslung M320 M4s

- [x] Remove RHS MAAWS Ammunition if a Vanilla MAAWS is equipped

### CODE REVIEW

**Comment by AndreasBrostrom** [comment]
We can add a weapon preference switch. I think it works for weapons as well as for items That whould force a specific MAAWS

**Review by Zarenx — CHANGES_REQUESTED** [review]
Replace all of the below: 
["rhs_mag_maaws_HE", 0],
["rhs_mag_maaws_HEAT", 0],

With these new ones:
["MRAWS_HE_F", 0],
["MRAWS_HEAT_F", 0],

**Comment by AndreasBrostrom** [comment]
> Replace all of the below: ["rhs_mag_maaws_HE", 0], ["rhs_mag_maaws_HEAT", 0],
> 
> With these new ones: ["MRAWS_HE_F", 0], ["MRAWS_HEAT_F", 0],

Fixed in other PR

**Comment by pool011** [comment]
Adding in Alpha loadouts now

**Pull request merged**
