### PR TITLE
Grammar/punctuation, remove veh/crate init functions

### PR DESCRIPTION
**Pull request by RaynorD**
Assuming the CBA class init event handlers work how I think they do (once set at mission start, will run specified code automatically on newly created objects). Also add arguments for starter crate.

### CODE REVIEW

**Comment by ColdEvul** [comment]
> Assuming the CBA class init event handlers work how I think they do (once set at mission start, will run specified code automatically on newly created objects). Also add arguments for starter crate.

Yes it suppose to do that. The thing is that Zeus messes things up when it comes to the script inventory changes for some reason.

Other thing that that is kind a good for the cba class is that it passes it through to child classes as well.

**Comment by RaynorD** [comment]
Gotcha. I wonder if we can wait until zeus is done with the box somehow. I'll see if I can find the code that handles that to see if there's a flag variable or anything.

**Comment by ColdEvul** [comment]
Set variable
If variable 
sleep 5
Add items? 

Or
Sleep 5
Add items?  

Or if empty crate add content.

**Comment by RaynorD** [comment]
Yep, so I'll look for a variable set by the zeus code that we can wait on that will indicate zeus has finished loading and populating the box. Worst case we could just sleep 5 or so.

**Comment by ColdEvul** [comment]
Could do Simular to this function: `fn_initCuratorHeloGetOutRL.sqf`

Or a `_x Setvariable GVAR(CrateFiler) `
And when this is present it changes the inventory. But only if crate is empty.

**Comment by ColdEvul** [comment]
Moving this discussion to a issue instead: #26

**Pull request merged**
