### PR TITLE
Re-implement TF47 Gear

### PR DESCRIPTION
**Pull request by Robot-Panda15**
- CHANGED:  RHS launchers to TF47 launchers

### CODE REVIEW

**Comment by Robot-Panda15** [comment]
@ColdEvul can you help me out with the conflicts? No idea what it's telling me

**Comment by ColdEvul** [comment]
Sure i can fix it tomorrow. It's a easy fix

**Comment by ColdEvul** [comment]
sceptical regarding TF47

**Comment by ColdEvul** [comment]
updated after merge

**Pull request closed without merging**
