### PR TITLE
Starter Crate Rework

### PR DESCRIPTION
**Pull request by Robot-Panda15**
Rework the Starter Crates

### CODE REVIEW

**Comment by ColdEvul** [comment]
some of thoes items should go in to Bravo or Charlie alpha don't need a boxes of bin pilot grade objects

**Comment by Robot-Panda15** [comment]
Nah, PMAGs for all I think

**Comment by ColdEvul** [comment]
I'll prefere STANAG for global and charlie with PMAG if its unclear

**Comment by ColdEvul** [comment]
#526 tasking over

**Pull request closed without merging**
