### PR TITLE
Complete restructure of the loadout system as well as some minor fixes

### PR DESCRIPTION
**Pull request by ColdEvul**

### CODE REVIEW

**Comment by RaynorD** [comment]
Where's the specification for this request? Don't see any requests from Argus about this.

**Comment by ColdEvul** [comment]
It been a long going project form Argus side.
I just punched it so he don't need to make a account.

**Comment by RaynorD** [comment]
Cool. It may also be easier to tackle #72 if we build it into a brand new system built to include it.

**Comment by ColdEvul** [comment]
Yes that is the idea I'm currently in the process of setting that upp.

**Comment by ColdEvul** [comment]
Also this pull will have merge conflict galore cause there are allot of changes done with one pull.
Will also make sure this is up to date with the master to ease upp some of the pain.

**Comment by ColdEvul** [comment]
Manual Merged

**Pull request closed without merging**
