### PR TITLE
Supply Crate Update

### LINKED ISSUE #315: Reconvert RHS MAAWS and launchers to TF47
Once Grey's patch is added to CAVPACK

### PR DESCRIPTION
**Pull request by Robot-Panda15**
**When merged this pull request will:**
Add M62 M240 tracer boxes
Replace RHS MAAWS with TF47 MAAWS - fixes #315 
Add APERS Mine Dispenser

### CODE REVIEW

**Comment by Robot-Panda15** [comment]
spoke with Tully about it already. This is stuff that needs to be added regardless, so it's been approved already

**Comment by Robot-Panda15** [comment]
Hold.  `cav_m3maaws_heat_cs` is not in yet. just had to remove it from my current mission file in order for it to work.

**Comment by Robot-Panda15** [comment]
> Hold. `cav_m3maaws_heat_cs` is not in yet. just had to remove it from my current mission file in order for it to work.

Talked with Grey, CavAddon version needs to be updated on the workshop before this cScripts fix is submitted.

**Comment by ColdEvul** [comment]
Yes correct its added to the mod repo but not released on the workshop. There are a cupple of more things that need to be sorted out first. 

Basicly nothing in the dev build repo work atm due to unimplemented mod stuff.

**Comment by ColdEvul** [comment]
Note:
Merge in to new system in progress. This will be closed and once it's done.

**Pull request closed without merging**
